GET http://localhost:3000/movies/
###
GET http://localhost:3000/movies/:movieId
###
POST http://localhost:3000/movies/
Content-Type: application/json

{
  "directorId": 6,
  "movieName": "JurassicPark",
  "leadActor": "Jeff Goldblum"
}
###
PUT http://localhost:3000/movies/:movieId